Fix the batch.size condition on the produce path
edenhill/librdkafka pull request #4056
Opened 2022-11-08 23:48 UTC by travisdowns

When the batch.size is exceeded, we will close and send the current batch. In case compression is enabled, we "inflate" the batch size by 8x for the purposes of this check.

At least, that's the intent. Currently the condition is reversed: the 8x inflation happens if compression is disabled, not the other way around. The effect is that messages linger for longer than expected in the queue, as if the batch size was 8x larger. They are still sent respecting the batch size however, since this occurs at a different location.

This change reverses the sense of the condition so that the 8x multiplier is applied iff compression is enabled.

2022-11-09 15:07 UTC, edenhill commented
Whoa, good find!

2022-11-09 15:08 UTC, edenhill commented
I wonder if this has adverse effects on the compression case.. maybe we should not do the x8 at all, just to be safe.

2022-11-09 17:42 UTC, travisdowns commented
> I wonder if this has adverse effects on the compression case.. maybe we should not do the x8 at all, just to be safe.

I think it depends a bit on the write/send path: it separately respects `batch.size`, but is this the "before" or "after" compression figure?

If it is before compression, then I think this 8x doesn't make any sense at all. If it is after compression, then it seems that this 8x is a problem in the case that the compression ratio is lower: we won't even try to send the batch even though it is already starting to exceed the size: by the time we trigger `batch_ready` maybe there are 4 batches ready to send or whatever. 

In that case, if we used a multiplier of 1, I guess the impact is performance:  in "server" we will be constantly triggering the batch_ready condition but nothing gets sent.

I do think it makes sense to look at the Java client and as long as the behavior is reasonable there, I think there is a strong incentive to align the approach. In fact, this was discovered exactly when switching from the Java client and then noting the sudden change in behavior.

2022-11-09 18:08 UTC, edenhill commented
There's this WIP branch for adding streaming compression, which should alleviate this problem:
https://github.com/edenhill/librdkafka/tree/streamingcompr

It's a bit abandoned though, but it was working quite well in testing.
There was a lot of tuning of compression buffer sizes, and that's where it is currently at.

2022-11-09 19:50 UTC, travisdowns commented
I guess the safest approach would be to use no multiplier since that's how it is effectively now (and I guess no one has complained) and I think that's how it was before the changes earlier this year that introduced this 8x multiplier (from what I can tell, I didn't do deep research on whether this also existed somewhere else before) and I _think_ it is consistent with the Java client.

2022-11-09 22:23 UTC, edenhill commented
Yep, I agree. Rip it out

2022-11-15 00:38 UTC, travisdowns commented
@edenhill - new push with no multiplier regardless of whether compression is enabled or not.

2022-11-15 13:23 UTC, edenhill requested changes
There is another call down at line 3970

2022-11-15 17:29 UTC, travisdowns commented
@edenhill oops, good catch! Fixed that one too.

2022-11-15 19:20 UTC, merged

2022-11-15 19:20 UTC, edenhill commented
Very good, thank you!